sudo: required
services:
  - docker

before_install:
  - docker build -t idrmic/kubernetes-udemy -f Dockerfile.dev .

script:
  - docker run -e CI=true idrmic/kubernetes-udemy npm run test
  